<a href="https://colab.research.google.com/github/arsen-git/Colaboratory-Repo/blob/master/spiral.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

In [0]:
def ZeroLocation(matrix):
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if matrix[i][j] == 0:
                return (i, j)

    return (-1, -1)

In [0]:
def HowManyZero(matrix):
    count_zero, a = 0, 0
    for i in range(len(matrix[0])):
        if matrix[a][i] == 0:
            count_zero += 1
        else:
            a += 1
            i = 0

    return count_zero

In [0]:
def Fill(matrix, progress, total_zero, rowL, colL):
    """ Vertical filling operation. """
    for i in range(total_zero):
        matrix[0+rowL][i+colL] = progress
        progress += 1
    
    return matrix, progress

In [0]:
def Reverse(matrix):
    """ Reverse operation. """
    row, column = matrix.shape[0], matrix.shape[1]
    new_matrix = np.zeros(row*column, dtype=int).reshape(row, column)
    
    r = 0
    for i in range(row-1, -1, -1):
        new_matrix[r] = matrix[i]
        r+=1
    
    return new_matrix

In [0]:
def Transpose(matrix):
    """ Transposition of the matrix. """
    row, column = matrix.shape[0], matrix.shape[1]
    new_matrix = np.zeros(row*column, dtype=int).reshape(column, row)

    for i in range(column):
        for j in range(row):
            new_matrix[i][j] = matrix[j][i]
    
    return new_matrix

In [30]:
def main():
    row, column, progress, count = 15, 15, 1, 0
    matrix = np.zeros((row, column), dtype=int)
    rowL, colL = ZeroLocation(matrix)

    while rowL != -1 and colL != -1:
        matrix = Reverse(Transpose(matrix))
        total_zero = HowManyZero(matrix)
        rowL, colL = ZeroLocation(matrix)
        matrix, progress = Fill(matrix, progress, total_zero, rowL, colL)

    while matrix[0][0] != 1:
        matrix = Reverse(Transpose(matrix))
    print(matrix)
    
if __name__ == '__main__':
    main()

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 56  57  58  59  60  61  62  63  64  65  66  67  68  69  16]
 [ 55 104 105 106 107 108 109 110 111 112 113 114 115  70  17]
 [ 54 103 144 145 146 147 148 149 150 151 152 153 116  71  18]
 [ 53 102 143 176 177 178 179 180 181 182 183 154 117  72  19]
 [ 52 101 142 175 200 201 202 203 204 205 184 155 118  73  20]
 [ 51 100 141 174 199 216 217 218 219 206 185 156 119  74  21]
 [ 50  99 140 173 198 215 224 225 220 207 186 157 120  75  22]
 [ 49  98 139 172 197 214 223 222 221 208 187 158 121  76  23]
 [ 48  97 138 171 196 213 212 211 210 209 188 159 122  77  24]
 [ 47  96 137 170 195 194 193 192 191 190 189 160 123  78  25]
 [ 46  95 136 169 168 167 166 165 164 163 162 161 124  79  26]
 [ 45  94 135 134 133 132 131 130 129 128 127 126 125  80  27]
 [ 44  93  92  91  90  89  88  87  86  85  84  83  82  81  28]
 [ 43  42  41  40  39  38  37  36  35  34  33  32  31  30  29]]
