In [2]:
import numpy as np

### NUMPY-2 ARRAY CREATİON (DİZİ OLUŞTURMA)

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

• .array fonksiyonu ile .ndarray olmayan bir diziyi .ndarray nesnesine dönüştürüyoruz.

In [5]:
a.dtype

dtype('int64')

• dtype('int64') .ndarray içerisindeki veri tipini döndürür.

In [6]:
b = np.array([1., 2., 3., 4.])
b

array([1., 2., 3., 4.])

• Görüldüğü üzere dizi içindeki elemanlara baktığımızda 1., 2. ile integer olan değeri biz float değere çevirebiliriz.

In [8]:
b.dtype

dtype('float64')

In [11]:
#c = np.array(1,2,3)

•Yukardaki kullanım yanlıştır. Bir dizi tanımlamak için iki farklı yol vardır.
Bunlar:

In [14]:
c = np.array([1,2,3]) # [] kullanmak veya
c = np.array((1,2,3)) # () kullanmaktır. Sonuç 2 türlü de aynıdır.

In [16]:
d = np.array([1., 2, 3, 4, 5])
d

array([1., 2., 3., 4., 5.])

• Bir dizi içerisinde en az 1 tane float değer varsa tüm değerler float değere dönüştürülür.

In [18]:
e = np.array([1, 2, 3], dtype=complex)
e

array([1.+0.j, 2.+0.j, 3.+0.j])

• Bir diziyi tanımlarken veri tipini de seçebiliriz. Bunu yukardaki dtpye='veri_tipi' parametresi ile yapabiliriz:

In [20]:
f = np.array([1., 2, 3.], dtype=int)
f

array([1, 2, 3])

• Aslında f değişkeni bir float64 türünde veri barındırıyor ancak biz değişken içerisinde dtype = ile o değişken içerisindeki elemanları int64 veri tipine dönüştürdük

In [23]:
g = np.zeros((3, 4))
g

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

• Yukarda 3 satırlık ve 4 sütunluk bir dizi oluşturduk ve .zeros ile tüm içeriği float veri tipinde 0 lardan oluşan bir değişken oluşturduk.

In [29]:
h = np.ones((2, 3, 4), dtype=np.int16)
print(h)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


• Buradaki önemli olan nokta .ones(x, y, z) parametrelerinden:

    x: kaç tane dizi oluşturulacağı
    y: kaç satırlık dizi olacağı
    z: kaç sütunluk dizi olacağını belirtir.

• dtpye = np.int16 ise numpy içerisindeki int16 veri tipine dönüştür demektir.

• İşlem sonunda dizinin tüm elemanlarının içeriği 1 rakamlarından oluşmaktadır.

In [31]:
i = np.empty((2,3))
i

array([[9.9004273e-317, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

• .empty, ilk içeriği rastgele olan ve belleğin durumuna bağlı bir dizi oluşturur.

In [33]:
j = np.arange(2, 30 ,2)
j

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

• Basit python range() fonksiyonu mantığı 2 den 30 a kadar 2 şer 2 şer atla. :)

In [35]:
k = np.arange(0, 2, 0.1)
k

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

• 0 dan 2 ye kadar 0.1 er şekilde atlayarak liste oluştur. :)

In [37]:
l = np.linspace(0, 2, 9)
l

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

• Buradaki mantık ise şudur: 
    
    0 dan 2 ye kadar (tüm reel sayılar) 9 tane değer oluştur.

____________________________________________________

# Ayrıca Bakınız:

	• array,
	• zeros,
	• zeros_like,
	• ones,
	• ones_like,
	• empty,
	• empty_like,
	• arange,
	• linspace,
	• numpy.random.rand,
	• numpy.random.randn,
	• fromfunction,
	• fromfile	