In [60]:
import numpy as np

## NUMPY-4 BASIC OPERATIONS (TEMEL İŞLEMLER)

In [61]:
a = np.array([20,30,40,50])
a

array([20, 30, 40, 50])

In [62]:
b = np.array([0,1,2,3])
b

array([0, 1, 2, 3])

In [63]:
a-b

array([20, 29, 38, 47])

• Çıkarma işlemine dikkat edin.
b dizisi içerisindeki değerleri, a dizisi içerisindeki değerlerden çıkarıyor.

         [0 1 2 3]
         [20 29 38 47]

• 20 den 0 | 30 dan 1 | 40 dan 2 | 50 den 3 çıkarılıyor.

In [64]:
b**2

array([0, 1, 4, 9])

• Basit aritmetik işlemler tüm dizinin elemanları için uygulanır.

In [65]:
a < 40

array([ True,  True, False, False])

• Klasik karşılaştırma işleçleri diziler için uygulanabilir. 

In [66]:
A = np.array( [[1,1],
               [0,1]] )
A

array([[1, 1],
       [0, 1]])

In [67]:
B = np.array( [[2,0],
               [3,4]] )
B

array([[2, 0],
       [3, 4]])

In [68]:
A*B

array([[2, 0],
       [0, 4]])

• Yukardaki sonuç bir 'elementwise' ürünüdür

In [69]:
A@B

array([[5, 4],
       [3, 4]])

• Yukardaki sonuç ise bir 'matris' ürünüdür. Veya bunu şu şekildede yapabiliriz:

In [70]:
A.dot(B)

array([[5, 4],
       [3, 4]])

______________________________________


• += Ve *= gibi bazı işlemler, yeni bir tane oluşturmak yerine mevcut bir diziyi değiştirmek için uygulanabilir.

In [71]:
x = np.ones((2,3), dtype=int)
x

array([[1, 1, 1],
       [1, 1, 1]])

In [72]:
y = np.random.random((2,3))
y

array([[0.61979185, 0.1054678 , 0.82889195],
       [0.96712962, 0.55255014, 0.4010096 ]])

In [73]:
x *= 3
x

array([[3, 3, 3],
       [3, 3, 3]])

In [74]:
y += x
y

array([[3.61979185, 3.1054678 , 3.82889195],
       [3.96712962, 3.55255014, 3.4010096 ]])

• x += y otomatik olarak tamsayı türüne dönüştürülmez

• İşlem yaparken veri türlerini bilmemiz ve ona göre işlemler yapmamız gerekiyor.

In [76]:
g = np.ones(3, dtype=np.int32)
g

array([1, 1, 1], dtype=int32)

•.ones(3 => 3 tane 1 oluşturur.

______________________________________________________________________-


• Dizideki tüm öğelerin toplamının hesaplanması gibi birçok tek taraflı işlem ndarray sınıfıdır.

In [81]:
k = np.array([1,2,3,4,5,6,7,8,9,10])
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
k.sum() # Tüm dizinin toplamı.

55

In [83]:
k.min() # Dizinin en küçük elemanı.

1

In [85]:
k.max() # Dizinin en büyük elemanı.

10

• Varsayılan olarak, bu işlemler dizisine, şekline bakılmaksızın 
bir sayı listesi gibi uygulanır. Ancak, axis parametresini
belirterek bir dizinin belirtilen ekseni boyunca bir işlem
uygulayabilirsiniz:

In [86]:
n = np.arange(12).reshape(3, 4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
n.sum(axis=0) # 0 x ekseni.

array([12, 15, 18, 21])

• Her sütunun toplamı

 	Sırasıyla sütunlar toplanır:

 	0 + 4 + 8 = 12 | 1 + 5 + 9 = 15 | 2 + 6 + 10 = 18 | 3 + 7 + 11 = 21

	Sonuç:
 		[12 15 18 21]

In [88]:
n.min(axis=0)

array([0, 1, 2, 3])

• Dizideki minumum elemanların olduğu satır.

In [97]:
n.min(axis=1) # 1 y ekseni

array([0, 4, 8])

• Dizideki minumum elemanların olduğu sütun.

In [90]:
n.max(axis=0)

array([ 8,  9, 10, 11])

• Dizideki maximum elemanların olduğu satır.

In [91]:
n.max(axis=1)

array([ 3,  7, 11])

• Dizideki maximum elemanların olduğu sütun.

In [94]:
n.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [95]:
n.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

	[[ 0  1  2  3]
 	[ 4  5  6  7]
 	[ 8  9 10 11]]

 	Sırasıyla:

 	0 = 0
 	0 + 1 = 1
 	0 + 1 + 2 = 3
 	0 + 1 + 2 + 3 = 6
	
	 4 = 4
	 4 + 5 = 9
	 4 + 5 + 6 = 15
	 4 + 5 + 6 + 7 = 22

	 8 = 8
	 8 + 9 = 17
	 8 + 9 + 10 = 27
	 8 + 9 + 10 + 11 = 38

	Sonuç:
		[[ 0  1  3  6]
 		[ 4  9 15 22]
 		[ 8 17 27 38]]