In [1]:
import numpy as np

# NUMPY-5 UNIVERSAL FUNCTIONS (EVRENSEL FONKSİYONLAR)

•NumPy: sin, cos, exp gibi matematiksel fonksiyonlar sağlar.

•Numpy içerisinde bunlara 'universal functions(ufunc)' denir.

•NumPy içinde, bu fonksiyonlar bir dizi üzerinde çıkış olarak bir dizi
üreten elementwise olarak çalışır.

In [3]:
a = np.array([1, 4, 16, 25, 49])
a

array([ 1,  4, 16, 25, 49])

In [4]:
np.sqrt(a)

array([1., 2., 4., 5., 7.])

In [5]:
np.exp(a)

array([2.71828183e+00, 5.45981500e+01, 8.88611052e+06, 7.20048993e+10,
       1.90734657e+21])

In [6]:
b = np.array([1, 2, 3, 4, 5])
b

array([1, 2, 3, 4, 5])

In [7]:
np.add(b, a)

array([ 2,  6, 19, 29, 54])

• .add fonksiyonu şuna benzerdir: a+b

__________________________________________________________________

# Ayrıca Bakınız:

	all,
	any,
	apply_along_axis,
	argmax,
	argmin,
	argsort,
	average,
	bincount,
	ceil,
	clip,
	conj,
	corrcoef,
	cov,
	cross,
	cumprod,
	cumsum,
	diff,
	dot,
	floor,	
	inner,
	inv,
	lexsort,
	max,
	maximum,
	mean,
	median,
	min,
	minimum,
	nonzero,
	outer,
	prod,
	re,
	round,
	sort,
	std,
	sum,
	trace,
	transpose,
	var,
	vdot,
	vectorize,
	where