In [130]:
import numpy as np

# NUMPY-6 INDEXING, SLICING and ITERATING (DİZİNLEME, DİLİMLEME ve YİNELEME)

• Tek boyutlu diziler, dizinler ve diğer Python dizileri gibi dizinlenebilir, dilimlenebilir ve yinelenebilir.

In [131]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [132]:
a[2], a[3], a[5], a[-1], a[0]

(8, 27, 125, 729, 0)

In [133]:
a[2:5]

array([ 8, 27, 64])

In [134]:
a[0:6:2]

array([ 0,  8, 64])

• Yukardaki dilimlemede sırasıyla 0 dan başla 6 ya kadar git (6 dahil değil) 2 şer 2 şer atlayarak.

In [135]:
a[0:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

• Yukardaki dilimlemede 0 dan 6 ya kadar olan elemanlar arasında 2 şer 2 şer atlanan değerleri -1000 ile değiştir.

In [136]:
a[: : -1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

• a yı tersine çevir.

In [137]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/lib/python3/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


_________________________________________________

•Çok boyutlu diziler, eksen başına bir dizine sahip olabilir. Bu indisler virgüllerle ayrılmış bir dizgede verilmiştir:

In [138]:
def f(x, y):
    return 10*x+y
b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [139]:
b[2,3]

23

• b nin 2. satırındaki 3. sütun

In [140]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

• b nin 0 ile 5. indisler arası (satır), 1.sütunun tamamı

In [141]:
b[: :, 1]

array([ 1, 11, 21, 31, 41])

• Önceki örneğe eşdeğer

In [142]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

• b'nin ikinci ve üçüncü satırındaki her sütun

In [143]:
b[-1]

array([40, 41, 42, 43])

• Yukardakine eş değerdir.

In [144]:
b[-1:]

array([[40, 41, 42, 43]])

________________________________________
• Noktalar (...), tam bir indeksleme zinciri üretmek için ihtiyaç duyulan sayıda kolonu temsil eder.
Örneğin, x bir 5 eksenli dizi, ardından

    • x[1,2,...] birbirine eşdeğerdir x[1,2,:,:,:],
    • x[...,3] için x[:,:,:,:,3] ve
    • x[4,...,5,:] için x[4,:,:,5,:].

In [145]:
c = np.array( [[[ 0, 1, 2],
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

• 3B dizi (iki adet yığılmış 2B dizi)

In [146]:
c.shape

(2, 2, 3)

• Yukardaki çıktının anlamı şudur:

    • 2 tane 2 satırlık ve 3 sütunluk diziler oluştur. Dizinin eleman sayısı (x, y, z) için x*y*z olmalıdır.

In [147]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

• c [1,:,:] veya c [1] ile aynıdır.

In [148]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

• c[:,:,2] ile eşdeğerdir.

_______________________________________________


•Çok boyutlu diziler üzerinde yineleme, birinci eksene göre yapılır:

In [149]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


• Bununla birlikte, biri dizideki her öğe üzerinde bir işlem yapmak istiyorsak .flat özniteliği kullanılabilir.

In [150]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
