In [2]:
import numpy as np

# NUMPY-7 SHAPE MANIPULATION (ŞEKİL MANİPÜLASYONU)

   ### 1-Changing the shape of an array (Bir dizinin şeklini değiştirme)

In [3]:
a = np.arange(20).reshape(5, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [4]:
b = np.floor(10*np.random.random((3,4)))
print(b)

[[6. 7. 7. 0.]
 [9. 8. 6. 0.]
 [0. 7. 6. 2.]]


In [5]:
print(b.shape)

(3, 4)


• Dizinin kaç satır ve sütundan oluştuğunu döndüren fonksiyon.

In [6]:
print(b.ravel())

[6. 7. 7. 0. 9. 8. 6. 0. 0. 7. 6. 2.]


• Dizinin tek boyutlu hali, basık hali.

In [7]:
print(b.reshape(6, 2))

[[6. 7.]
 [7. 0.]
 [9. 8.]
 [6. 0.]
 [0. 7.]
 [6. 2.]]


• Diziyi yeniden boyutlandırır ancak ana dizide değişiklik olmaz.

In [8]:
print(b.T)

[[6. 9. 0.]
 [7. 8. 7.]
 [7. 6. 6.]
 [0. 0. 2.]]


• Bir dizinin transpozunu yani satırların sütun, sütunların ise satır olduğu hale denir.

In [9]:
print(b.T.shape)

(4, 3)


• Transpozu alınmış bir dizinin kaç satır ve sütundan oluştuğunu döndüren değer.

In [11]:
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [12]:
print(a.reshape(4, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


• Geçici olarak .reshape ile yeniden boyutlandırıyoruz, kalıcı olarak boyutlandırmak için:

In [13]:
a.resize((10,2))

In [14]:
print(a.reshape(5, -1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


• Bir boyut -1 olarak atanırsa diğer boyutlar otomatik olarak hesaplanır.