In [2]:
import numpy as np

# NUMPY-8 SHAPE MANIPULATION (ŞEKİL MANİPÜLASYONU)

### 2-Stacking together different arrays (Farklı dizileri bir araya getirme) 

• Farklı eksenler boyunca birkaç dizi birlikte istiflenebilir:

In [3]:
a = np.floor(10*np.random.random((2,2)))
print(a)

[[8. 6.]
 [8. 0.]]


In [4]:
b = np.floor(10*np.random.random((2,2)))
print(b)

[[1. 0.]
 [2. 3.]]


In [58]:
print(np.vstack((a, b)))

[[3. 8.]
 [7. 6.]
 [2. 2.]
 [4. 7.]]


• Vertical yığma, yani dikey olarak.

In [59]:
print(np.hstack((a,b)))

[[3. 8. 2. 2.]
 [7. 6. 4. 7.]]


• Horizontal yığma, yani yatay olarak. 

In [6]:
from numpy import newaxis

• Column_stack işlevi 1D dizilerini 2D dizisine sütunlar(kolonlar) olarak istifler.

• Sadece 2D diziler için hstack'e eşdeğerdir:


In [61]:
print(np.column_stack((a,b)))

[[3. 8. 2. 2.]
 [7. 6. 4. 7.]]


• 2D dizili.

In [73]:
x = np.array([1., 2.]) # 1 boyutlu dizi
y = np.array([4., 5.]) # 1 boyutlu dizi

print(np.hstack((x, y))) # hstack kullandığımızda 1 boyutlu dizileri sadece 1D olarak ayarlayabiliriz ancak:

[1. 2. 4. 5.]


In [71]:
print(np.column_stack((x,y)))

[[1. 4.]
 [2. 5.]]


• 2 boyutlu bir dizi döndürür.

In [64]:
print(np.hstack((x,y)))

[1. 2. 4. 5.]


• Sonuç farklıdır.

In [79]:
print(x[:,newaxis])

[[1.]
 [2.]]


In [66]:
print(np.column_stack((x[:,newaxis], y[:,newaxis])))

[[1. 4.]
 [2. 5.]]


In [67]:
print(np.hstack((x[:,newaxis], y[:,newaxis])))

[[1. 4.]
 [2. 5.]]


• Sonuç aynıdır, yukardaki ile.

In [68]:
print(np.r_[1:4, 0, 4])

[1 2 3 0 4]


In [69]:
print(np.c_[1:4])

[[1]
 [2]
 [3]]
