In [28]:
import numpy as np

# NUMPY-10 COPIES and VIEWS(KOPYALAR ve GÖRÜNÜMLER)

• Dizileri çalıştırırken ve işlerken, verileri bazen yeni bir diziye kopyalanır, bazen de kopyalanmaz.
Genelde 3 sorun vardır.

##### 1- No Copy at All (Hiç kopya yok)

• Basit atamalar, dizi nesnelerinin veya verilerinin kopyasını almaz.


In [29]:
a = np.arange(12)

In [30]:
b = a

• Yeni nesne oluşturulmadı.

In [31]:
b is a

True

• a ve b, aynı ndarray nesnesi için iki addır.

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
a.shape

(12,)

In [35]:
b.shape

(12,)

In [36]:
b.shape = 3,4
b.shape

(3, 4)

• b yi 3 e 4 lük bir matris haline döndürdük.

In [37]:
a.shape

(3, 4)

• a değişkeninin de şekli değişir.

• Python değişken nesneleri referans olarak iletir, işlev çağrıları kopya yapmaz.

In [38]:
def f(x):
    print(id(x))

id(a) # id, bir nesnenin benzersiz bir tanımlayıcısıdır
f(a)
    

139943996408096


__________________________________________________________________________________-
##### 2-View or Shallow Copy (Görüntüle veya Sığ Kopya)

•Farklı dizi nesneleri aynı verileri paylaşabilir.

•View yöntemi aynı görünen yeni bir dizi nesnesi oluşturur.

In [39]:
c = a.view()
c is a

False

In [40]:
c.base is a

True

• c sahip olunan verinin bir görünümüdür.

In [41]:
c.flags.owndata

False

In [42]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [43]:
c.shape = 2, 6

In [44]:
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [45]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


• a nın şekli değişmez.

In [46]:
c[0, 4] = 1234

In [47]:
a 

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

•a nın sadece verileri değişir.

In [48]:
s = a[ : , 1:3] # Daha net görünmesi açısından eklenen boşluk karakterleri.
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

____________________________________________________________________________-
##### 3-Deep Copy (Derin Kopya)

• Bu kopya yöntemi, dizinin ve verilerinin eksiksiz bir kopyasını oluşturur.

In [57]:
d = a.copy()

• Yeni verilerle yeni bir dizi nesnesi oluşturulur

In [50]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [51]:
d

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [52]:
a is d

False

In [53]:
d.base is a

False

• a ile hiçbirşey paylaşmıyor.

In [54]:
d[0,0] = 9999

In [55]:
d

array([[9999,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [56]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

• Görüldüğü üzere a daki herhangi bir veri değiştirilmedi.